name: Common setup and cleaning
description: Setup necessary environments and clean the runner's temp path on ending
inputs:
  job_type:
    description: the name to use in the TEMP_PATH and REPO_COPY
    default: common
    type: string
  nested_job:
    description: the fuse for unintended use inside of the reusable callable jobs
    default: true
    type: boolean
runs:
  using: "composite"
  steps:
    - name: Setup and post-clean
      uses: ./.github/actions/with-post-step
      with:
        main: |
          echo "Setup the common ENV variables"
          cat >> "$GITHUB_ENV" << 'EOF'
          TEMP_PATH=${{runner.temp}}/${{inputs.job_type}}
          REPO_COPY=${{runner.temp}}/${{inputs.job_type}}/${{github.repository.name}}
          EOF
          if [ -z "${{env.GITHUB_JOB_OVERRIDDEN}}" ] && [ "true" == "${{inputs.nested_job}}" ]; then
            echo "The GITHUB_JOB_OVERRIDDEN ENV is unset, and must be set for the nested jobs"
            exit 1
          fi
        post: |
          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
          sudo rm -fr "${{runner.temp}}"
